#!/usr/sww/bin/python3

print('Content-type: text/html')
print('')

print('<H1>Hello!</H1>')
import os, subprocess
print('imported...')
print('<code>')
print('')
print('PWD:')
print(os.getcwd())
print('')
print(os.chdir('../labs'))
print('CD:')
print(os.getcwd())
print('')
print(subprocess.getoutput('/usr/sww/bin/git reset --hard'))
print(subprocess.getoutput('/usr/sww/bin/git submodule foreach git reset --hard'))
print('Reset.')
print('')
print(subprocess.getoutput('GIT_SSL_NO_VERIFY=true /usr/sww/bin/git pull'))
print('pulled')
# TODO: Determine if git submodule init must be run?
print('')
print(subprocess.getoutput('GIT_SSL_NO_VERIFY=true /usr/sww/bin/git submodule update'))
print('update submodules')
print('')
print(subprocess.getoutput('chmod -R 755 .'))
print('permissions updated.')
print('')
print(subprocess.getoutput('../webhooks/scripts/bjcr_urls.py'))
print('')
print('urls fixed.')
print('</code>')
